# Makefile -
#

OBJS = ffsLib.o taskLib.o taskHookLib.o errnoLib.o kernQLib.o memPartLib.o \
       memLib.o semBLib.o semCLib.o kernLib.o taskVarLib.o rtosLib.o eventLib.o \
       kernTickLib.o msgQLib.o semLib.o schedLib.o semMLib.o semRWLib.o \
       msgQEvLib.o semEvLib.o taskShow.o taskInfo.o memShow.o eventShow.o \
       taskHookShow.o msgQShow.o semShow.o wdLib.o wdShow.o
SUBDIRS =
LIB_TGT = rtos

include $(RTOS_BASE)/include/make/buildDefaults.mk
