# Makefile -
#

OBJS = netBufLib.o netShow.o netLib.o sockLib.o bsdSockLib.o domainLib.o \
       mbufLib.o soLib.o ifLib.o radixLib.o routeLib.o rawLib.o unixDomainLib.o
SUBDIRS =
LIB_TGT = net

include $(RTOS_BASE)/include/make/buildDefaults.mk
