OBJS = dllLib.o objLib.o sllLib.o listLib.o qLib.o qFifoLib.o qPrioLib.o \
       qPriBmpLib.o qMsgLib.o ringLib.o objLib.o classLib.o hashLib.o \
       classShow.o cksumLib.o historyLog.o

SUBDIRS =
LIB_TGT = util

include $(RTOS_BASE)/include/make/buildDefaults.mk
