# Makefile -
#

OBJS = rawFsLib.o rt11FsLib.o \
       dosFsLib.o dosDirLib.o dosFatLib.o dosSuperLib.o dosFmtLib.o dosFsShow.o
SUBDIRS =
LIB_TGT = oldfs

include $(RTOS_BASE)/include/make/buildDefaults.mk
