# Makefile -
#

OBJS = fflush.o setvbuf.o fread.o fwrite.o printf.o scanf.o puts.o fopen.o \
       fdopen.o fclose.o getc.o fgetc.o fgets.o getchar.o putc.o fputc.o \
       putchar.o feof.o ferror.o gets.o ungetc.o
SUBDIRS =
LIB_TGT = stdc

include $(RTOS_BASE)/include/make/buildDefaults.mk
