# Makefile -
#

OBJS = udvgabmp.o udvgaclr.o udvgagc.o udvgapix.o udvgaxpix.o \
       udvga.o udvgadev.o udvgainf.o udvgaxbmp.o
SUBDIRS =
LIB_TGT = ugl-driver

include $(RTOS_BASE)/include/make/buildDefaults.mk
