# Makefile -
#

OBJS = ioLib.o iosLib.o iosShow.o ttyLib.o cbioLib.o cbioShow.o \
       pathLib.o ioFsLib.o dirLib.o nullDrvLib.o uioLib.o
SUBDIRS =
LIB_TGT = io

include $(RTOS_BASE)/include/make/buildDefaults.mk
