# Makefile -
#

OBJS = memchr.o memcmp.o memcpy.o memmove.o memset.o strcat.o strchr.o \
       strcmp.o strcpy.o strlen.o strncmp.o strncpy.o strpbrk.o strspn.o \
       strrchr.o strstr.o strtok_r.o strtok.o strdup.o memccpy.o strcspn.o \
       strncat.o
SUBDIRS =
LIB_TGT = stdc

include $(RTOS_BASE)/include/make/buildDefaults.mk
