OBJS =
SUBDIRS = arch fs io oldfs os libc libkern tools ugl util usr net netinet \
          rtos
LIB_TGT =

include $(RTOS_BASE)/include/make/buildDefaults.mk

purge:
	rm -fr $(RTOS_BASE)/lib/$(CPU)
