# Makefile -
#

OBJS = isalnum.o isalpha.o iscntrl.o isdigit.o isgraph.o islower.o isprint.o \
       ispunct.o isspace.o isupper.o isxdigit.o tolower.o toupper.o
SUBDIRS =
LIB_TGT = stdc

include $(RTOS_BASE)/include/make/buildDefaults.mk
