OBJS = bio.o erfLib.o file.o fsEventUtilLib.o fs_test.o mkfs.o ramdsk.o vfs.o \
       common.o fcalls.o  mount.o vnode.o fs.o
SUBDIRS = xbd
LIB_TGT = fs

include $(RTOS_BASE)/include/make/buildDefaults.mk
